#!/usr/bin/env bash
#
# Exports the *local* Supabase credentials into GITHUB_ENV.
#
# These keys are generated by `supabase start` from a fixed local development
# secret. They are not repository secrets and must never become any: they grant
# nothing beyond a throwaway container that exists for the length of one job.
# Adding them to the repository would be both unnecessary and a standing
# invitation to reuse them somewhere real.
#
# They are still masked in the log. A service-role key printed in CI output —
# even a local one — trains the eye to treat that shape of string as harmless,
# and this is the exact key whose real counterpart bypasses RLS.
#
# Reads `supabase status -o env`, the CLI's own machine-readable output, rather
# than scraping the human-readable table.

set -euo pipefail

status="$(pnpm exec supabase status -o env)"

# Parsed rather than `eval`-ed: this output is trusted, but a shell that
# evaluates whatever a subprocess prints is one CLI change away from surprising.
read_var() {
  printf '%s\n' "$status" | sed -n "s/^$1=\"\\(.*\\)\"\$/\\1/p"
}

api_url="$(read_var API_URL)"
anon_key="$(read_var ANON_KEY)"
service_role_key="$(read_var SERVICE_ROLE_KEY)"

# Fail loudly rather than exporting empty values. An empty credential would let
# the authorization suites run and fail deep inside a test with a confusing
# error, instead of stopping here with an obvious one.
for name in api_url anon_key service_role_key; do
  if [ -z "${!name}" ]; then
    echo "::error title=Supabase credentials unavailable::Could not read ${name} from \`supabase status -o env\`."
    echo "The local stack may not have started. Without this the authorization suites cannot run."
    exit 1
  fi
done

echo "::add-mask::$anon_key"
echo "::add-mask::$service_role_key"

{
  echo "NEXT_PUBLIC_SUPABASE_URL=$api_url"
  echo "NEXT_PUBLIC_SUPABASE_ANON_KEY=$anon_key"
  echo "SUPABASE_SERVICE_ROLE_KEY=$service_role_key"
} >>"$GITHUB_ENV"

echo "Exported local Supabase credentials for $api_url (values masked)."
