import { describe, expect, it } from "vitest";
import { evaluatePairings, type Mode } from "./contrast";
import { REQUIRED_COLOR_ROLES, readPalette, readTokensCss } from "./palette";

/**
 * ATL-008 — token sheet snapshot.
 *
 * The ticket asks for a visual snapshot of the token sheet in both modes. The
 * pixel snapshot lives in `tests/e2e/design-tokens.spec.ts` and needs a browser.
 *
 * This is the **equivalent documented verification that runs everywhere**: a
 * committed, human-readable sheet of every token value and every measured contrast
 * ratio. Any change to a token — deliberate or accidental — shows up as a reviewable
 * diff, including on machines and CI runners without browser binaries.
 *
 * Regenerate intentionally with `pnpm test -u` and review the diff.
 */

function buildTokenSheet(): string {
  const lines: string[] = [
    "# Atlas design token sheet",
    "",
    "GENERATED by `src/styles/token-sheet.test.ts` — do not edit by hand.",
    "Regenerate with `pnpm test -u` and review the diff.",
    "",
    "Source of truth: `src/styles/tokens.css` · Baseline: design system §2.1",
    "",
  ];

  // --- Colour roles ---------------------------------------------------------
  const light = readPalette("light");
  const dark = readPalette("dark");

  lines.push("## Semantic colour roles", "");
  lines.push("| Role | Light | Dark |", "| --- | --- | --- |");
  for (const role of REQUIRED_COLOR_ROLES) {
    lines.push(
      `| \`${role}\` | \`${light[role]?.toUpperCase()}\` | \`${dark[role]?.toUpperCase()}\` |`,
    );
  }
  lines.push("");

  // --- Contrast matrix ------------------------------------------------------
  for (const mode of ["light", "dark"] as Mode[]) {
    const results = evaluatePairings(readPalette(mode), mode);
    lines.push(`## Contrast matrix — ${mode} mode`, "");
    lines.push(
      "| Foreground | Background | Effective bg | Ratio | Min | Result |",
      "| --- | --- | --- | ---: | ---: | --- |",
    );
    for (const r of results) {
      const bg = r.backgroundAlpha === undefined ? r.background : `${r.background} @10%`;
      lines.push(
        `| \`${r.foreground}\` | \`${bg}\` | \`${r.effectiveBackground}\` | ${r.ratio.toFixed(2)} | ${r.minimum.toFixed(1)} | ${r.passes ? "PASS" : "FAIL"} |`,
      );
    }
    lines.push("");
  }

  // --- Non-colour scales ----------------------------------------------------
  const css = readTokensCss();
  const scale = (prefix: string, label: string) => {
    const rows = [...css.matchAll(new RegExp(`--${prefix}-([a-z0-9-]+):\\s*([^;]+);`, "g"))];
    const seen = new Set<string>();
    lines.push(`## ${label}`, "", "| Token | Value |", "| --- | --- |");
    for (const [, name, value] of rows) {
      if (name === undefined || value === undefined) continue;
      const key = `${prefix}-${name}`;
      if (seen.has(key)) continue;
      seen.add(key);
      lines.push(`| \`--${key}\` | \`${value.trim()}\` |`);
    }
    lines.push("");
  };

  scale("text", "Typography scale");
  scale("radius", "Radius tiers");
  scale("shadow", "Elevation");
  scale("duration", "Motion durations");
  scale("ease", "Motion easing");

  return lines.join("\n");
}

describe("token sheet", () => {
  it("matches the committed token sheet", async () => {
    await expect(buildTokenSheet()).toMatchFileSnapshot("./__snapshots__/token-sheet.md");
  });

  it("records a PASS for every pairing in both modes", () => {
    const sheet = buildTokenSheet();
    expect(sheet).not.toContain("| FAIL |");
    expect(sheet).toContain("| PASS |");
  });
});
