import { createClient, type PostgrestError, type SupabaseClient } from "@supabase/supabase-js";
import { afterAll, beforeAll, describe, expect, it } from "vitest";
import type { Database } from "@/types/database.generated";
import { FINDING_TYPES, isFindingTypeShape } from "@/lib/findings/findings";

/**
 * ATL-038 — authorization, deduplication, and schema integrity for
 * `privacy_findings`, against a real database.
 *
 * Four things only a database can settle:
 *
 *  1. **Two-user RLS**, with the unusual shape this table has: `authenticated`
 *     may read its own findings and write nothing at all. A finding is produced
 *     by a rule, not by a user (NFR-06), and resolving one must go through the
 *     service that also writes activity and recalculates the score (§11.1).
 *  2. **The dedup constraint.** §11.1 says a rule fires once per condition; the
 *     unique key is what makes that true when the engine is wrong.
 *  3. **The cross-user foreign key.** A plain `references digital_assets (id)`
 *     would allow a finding claiming one owner while pointing at another's
 *     asset — hidden from both by RLS, counted by the engine reading with
 *     service-role.
 *  4. **The lifecycle constraints**, which encode ADR-004's arithmetic: a
 *     resolved finding without a timestamp cannot sit in a trailing window, and
 *     a rule id without a version is unexplainable.
 *
 * Requires a running local Supabase (`pnpm db:start`). Fails rather than skips
 * when the database is absent — a skipped authorization test reads identically
 * to a passing one.
 */

const SUPABASE_URL = process.env.NEXT_PUBLIC_SUPABASE_URL ?? "http://127.0.0.1:54321";
const ANON_KEY = process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY ?? "";
const SERVICE_ROLE_KEY = process.env.SUPABASE_SERVICE_ROLE_KEY ?? "";

type TypedClient = SupabaseClient<Database>;
type FindingInsert = Database["public"]["Tables"]["privacy_findings"]["Insert"];

interface QueryResult {
  data: unknown;
  error: PostgrestError | null;
}

function describeError(error: PostgrestError): string {
  const parts = [`code=${error.code ?? "?"}`, `message=${error.message}`];
  if (error.details) parts.push(`details=${error.details}`);
  return parts.join(" | ");
}

function expectOk<R extends QueryResult>(result: R, context: string): NonNullable<R["data"]> {
  if (result.error) {
    throw new Error(`${context}: expected success but got ${describeError(result.error)}`);
  }
  if (result.data === null) throw new Error(`${context}: succeeded but returned no row`);
  return result.data as NonNullable<R["data"]>;
}

/** Passes when the operation was refused *or* silently matched nothing. */
function expectNoAccess(result: QueryResult, context: string): void {
  if (result.error) return;
  const rows = Array.isArray(result.data) ? result.data : result.data === null ? [] : [result.data];
  if (rows.length > 0) {
    throw new Error(`${context}: rows were reachable. ${rows.length} row(s).`);
  }
}

/** Passes only when the database refused. Used where a silent no-op would be wrong. */
function expectRejected(result: QueryResult, context: string): PostgrestError {
  if (!result.error) throw new Error(`${context}: expected the database to refuse, but it did not`);
  return result.error;
}

interface TestUser {
  id: string;
  client: TypedClient;
}

let admin: TypedClient;
let alice: TestUser;
let bob: TestUser;
let aliceAssetId: string;
let bobAssetId: string;
let aliceFindingId: string;
let bobFindingId: string;

/**
 * A resolution timestamp that is clearly in the past.
 *
 * `new Date().toISOString()` sits exactly on `privacy_findings_resolved_not_future`'s
 * boundary, and the two clocks either side of that comparison are not the same
 * one: the value is generated by Node with millisecond precision, while `now()`
 * is the Postgres transaction timestamp with microsecond precision. A run where
 * the app clock led the database's by microseconds failed here — `resolved_at`
 * `.369` against a `created_at` of `.368936` — which says nothing about the
 * lifecycle and everything about where the fixture was standing.
 *
 * An hour ago is unambiguously past under any plausible skew, and it makes the
 * negative cases below assert the constraint they name rather than accidentally
 * tripping this one. The future case deliberately keeps using `now + 1 day`.
 */
const RESOLVED_AT = new Date(Date.now() - 3_600_000).toISOString();

const uniqueKey = (label: string) =>
  `atl038-${label}-${Date.now().toString(36)}-${Math.random().toString(36).slice(2, 8)}`;

/**
 * A complete, valid finding, typed as the generated Insert row.
 *
 * Spread into an inline literal at every call site — `{ ...base(alice.id),
 * severity: "catastrophic" }` — so each override is checked against the column
 * it names, the way the ATL-027/028/029 authorization tests write their inserts.
 * An untyped payload builder would let a misspelled column reach the database as
 * a runtime error that looks like a schema defect.
 */
const base = (userId: string): FindingInsert => ({
  user_id: userId,
  finding_type: "hygiene",
  rule_id: "R-001",
  rule_version: "rules-v1",
  dedup_key: uniqueKey("key"),
  title: "A service has not been reviewed recently",
  description: "You have not confirmed what this service holds about you in over 180 days.",
  severity: "low",
  evidence_summary: "Last reviewed 2025-01-01.",
  recommended_action: "Review what this service holds.",
});

async function createUser(label: string): Promise<TestUser> {
  const email = `atl038-${label}-${Date.now()}@example.test`;
  const password = `Fixture-${label}-${Date.now()}`;

  const created = await admin.auth.admin.createUser({ email, password, email_confirm: true });
  if (created.error || !created.data.user) {
    throw new Error(`Could not create ${label}: ${created.error?.message ?? "no user returned"}`);
  }

  const client = createClient<Database>(SUPABASE_URL, ANON_KEY, {
    auth: { persistSession: false, autoRefreshToken: false },
  });
  const signIn = await client.auth.signInWithPassword({ email, password });
  if (signIn.error) throw new Error(`Could not sign in ${label}: ${signIn.error.message}`);

  return { id: created.data.user.id, client };
}

async function seedAsset(userId: string, serviceName: string): Promise<string> {
  const row = expectOk(
    await admin
      .from("digital_assets")
      .insert({ user_id: userId, service_name: serviceName, category: "social" })
      .select("id")
      .single(),
    `seeding an asset for ${userId}`,
  );

  return row.id;
}

beforeAll(async () => {
  if (!ANON_KEY || !SERVICE_ROLE_KEY) {
    throw new Error(
      "ATL-038 authorization tests require NEXT_PUBLIC_SUPABASE_ANON_KEY and " +
        "SUPABASE_SERVICE_ROLE_KEY. Run `pnpm db:start` and load .env.local.",
    );
  }

  admin = createClient<Database>(SUPABASE_URL, SERVICE_ROLE_KEY, {
    auth: { persistSession: false, autoRefreshToken: false },
  });

  const reachable = await admin.from("privacy_findings").select("id").limit(1);
  if (reachable.error) {
    throw new Error(
      `Cannot query public.privacy_findings as service_role at ${SUPABASE_URL}: ` +
        `${describeError(reachable.error)}. Run \`pnpm db:start\` and \`pnpm db:reset\`.`,
    );
  }

  alice = await createUser("alice");
  bob = await createUser("bob");

  aliceAssetId = await seedAsset(alice.id, "Alice Service");
  bobAssetId = await seedAsset(bob.id, "Bob Service");

  const aliceRow = expectOk(
    await admin
      .from("privacy_findings")
      .insert({ ...base(alice.id), asset_id: aliceAssetId })
      .select("id")
      .single(),
    "seeding alice's finding",
  );
  aliceFindingId = aliceRow.id;

  const bobRow = expectOk(
    await admin
      .from("privacy_findings")
      .insert({ ...base(bob.id), asset_id: bobAssetId, finding_type: "exposure" })
      .select("id")
      .single(),
    "seeding bob's finding",
  );
  bobFindingId = bobRow.id;
});

afterAll(async () => {
  /**
   * A loop with a truthiness guard rather than `filter(Boolean)`: the latter does
   * not narrow `(string | undefined)[]` to `string[]`, so it type-checks only by
   * accident. Deleting the user cascades their findings away, so no separate
   * delete is needed.
   */
  for (const user of [alice, bob]) {
    if (user?.id) await admin.auth.admin.deleteUser(user.id);
  }
});

describe("two-user isolation", () => {
  it("lets a user read their own findings", async () => {
    const rows = expectOk(
      await alice.client.from("privacy_findings").select("id"),
      "alice reading her own findings",
    );

    expect(rows.map((row) => row.id)).toContain(aliceFindingId);
  });

  it("hides another user's findings", async () => {
    expectNoAccess(
      await alice.client.from("privacy_findings").select("id").eq("id", bobFindingId),
      "alice reading bob's finding",
    );
  });

  it("hides them from an anonymous caller entirely", async () => {
    const anon = createClient<Database>(SUPABASE_URL, ANON_KEY, {
      auth: { persistSession: false, autoRefreshToken: false },
    });

    expectNoAccess(await anon.from("privacy_findings").select("id"), "anonymous reading findings");
  });
});

describe("findings are not user-authored", () => {
  it("refuses a client insert, even of the user's own row", async () => {
    /**
     * NFR-06: every finding is traceable to a rule, source, or model output. A
     * client-authored finding is traceable to nobody, and would deduct from the
     * user's own score through ADR-004's open-findings factor.
     */
    const result = await alice.client.from("privacy_findings").insert(base(alice.id)).select("id");

    expectRejected(result, "alice inserting her own finding");
  });

  it("refuses a client update of their own finding", async () => {
    /**
     * §11.1 requires resolution and dismissal to write an activity event and
     * feed score recalculation. A direct update would change the status while
     * skipping both — and would let a user write `resolved_by = 'system'`, an
     * assertion only the engine may make.
     */
    const result = await alice.client
      .from("privacy_findings")
      .update({ status: "dismissed", resolved_by: "user", resolved_at: new Date().toISOString() })
      .eq("id", aliceFindingId)
      .select("id");

    expectNoAccess(result, "alice dismissing her own finding directly");

    const after = expectOk(
      await admin.from("privacy_findings").select("status").eq("id", aliceFindingId).single(),
      "re-reading alice's finding",
    );
    expect(after.status).toBe("open");
  });

  it("refuses a client delete", async () => {
    const result = await alice.client
      .from("privacy_findings")
      .delete()
      .eq("id", aliceFindingId)
      .select("id");

    expectNoAccess(result, "alice deleting her own finding");

    const survivors = expectOk(
      await admin.from("privacy_findings").select("id").eq("id", aliceFindingId),
      "confirming the finding survived",
    );
    expect(survivors).toHaveLength(1);
  });

  it("still lets service_role write, which is how findings are made at all", async () => {
    const row = expectOk(
      await admin.from("privacy_findings").insert(base(alice.id)).select("id").single(),
      "service_role inserting a finding",
    );

    expect(row.id).toMatch(/^[0-9a-f-]{36}$/);
  });
});

describe("deduplication", () => {
  it("refuses a second finding with the same key for one user", async () => {
    // §11.1: "a rule fires once per condition". The constraint is what makes
    // that true when the engine is wrong.
    const key = uniqueKey("dup");
    expectOk(
      await admin
        .from("privacy_findings")
        .insert({ ...base(alice.id), dedup_key: key })
        .select("id")
        .single(),
      "first finding for the key",
    );

    const second = await admin
      .from("privacy_findings")
      .insert({ ...base(alice.id), dedup_key: key })
      .select("id");

    expect(expectRejected(second, "second finding for the same key").code).toBe("23505");
  });

  it("allows the same key for a different user", async () => {
    /**
     * The key is a hash of a rule and *that user's* entity scope. Scoping the
     * constraint per user rather than globally is what stops one user's finding
     * blocking another's identical condition.
     */
    const key = uniqueKey("shared");
    expectOk(
      await admin
        .from("privacy_findings")
        .insert({ ...base(alice.id), dedup_key: key })
        .select("id")
        .single(),
      "alice's finding",
    );

    expectOk(
      await admin
        .from("privacy_findings")
        .insert({ ...base(bob.id), dedup_key: key })
        .select("id")
        .single(),
      "bob's finding with the same key",
    );
  });
});

describe("cross-user foreign key", () => {
  it("refuses a finding pointing at another user's asset", async () => {
    const result = await admin
      .from("privacy_findings")
      .insert({ ...base(alice.id), asset_id: bobAssetId })
      .select("id");

    expect(expectRejected(result, "alice's finding pointing at bob's asset").code).toBe("23503");
  });

  it("allows a finding with no asset, for user-wide conditions", async () => {
    // R-008 (category_concentration) is about the whole footprint. Forcing it to
    // name one asset would make the finding say something it does not mean.
    expectOk(
      await admin
        .from("privacy_findings")
        .insert({ ...base(alice.id), asset_id: null, finding_type: "exposure" })
        .select("id")
        .single(),
      "a user-scoped finding",
    );
  });

  it("removes findings with the asset they describe", async () => {
    // ADR-001 requires a finding to cite the records it evaluated, so one whose
    // subject no longer exists cannot be explained — only displayed.
    const assetId = await seedAsset(alice.id, "Temporary Service");
    const row = expectOk(
      await admin
        .from("privacy_findings")
        .insert({ ...base(alice.id), asset_id: assetId })
        .select("id")
        .single(),
      "a finding about the temporary asset",
    );

    expectOk(
      await admin.from("digital_assets").delete().eq("id", assetId).select("id").single(),
      "deleting the temporary asset",
    );

    const survivors = expectOk(
      await admin.from("privacy_findings").select("id").eq("id", row.id),
      "looking for the finding afterwards",
    );
    expect(survivors).toHaveLength(0);
  });
});

describe("the lifecycle constraints", () => {
  /**
   * Written out rather than table-driven, so each payload is an inline literal
   * the compiler checks against its column.
   *
   * ADR-004 counts resolutions inside a trailing 180-day window, so a resolution
   * with no timestamp cannot be placed in it — and a resolver on an open finding
   * claims an ending that did not happen.
   */
  it("refuses a finding resolved with no resolver or time", async () => {
    const result = await admin
      .from("privacy_findings")
      .insert({ ...base(alice.id), status: "resolved" })
      .select("id");

    expect(expectRejected(result, "resolved with no resolver or time").code).toBe("23514");
  });

  it("refuses a finding dismissed with no resolver or time", async () => {
    const result = await admin
      .from("privacy_findings")
      .insert({ ...base(alice.id), status: "dismissed" })
      .select("id");

    expect(expectRejected(result, "dismissed with no resolver or time").code).toBe("23514");
  });

  it("refuses an open finding that already names a resolver", async () => {
    const result = await admin
      .from("privacy_findings")
      .insert({ ...base(alice.id), status: "open", resolved_by: "user" })
      .select("id");

    expect(expectRejected(result, "open but already resolved").code).toBe("23514");
  });

  it("refuses an in-progress finding carrying a resolution time", async () => {
    const result = await admin
      .from("privacy_findings")
      .insert({ ...base(alice.id), status: "in_progress", resolved_at: RESOLVED_AT })
      .select("id");

    expect(expectRejected(result, "in_progress with a resolution time").code).toBe("23514");
  });

  it("accepts a properly closed finding", async () => {
    expectOk(
      await admin
        .from("privacy_findings")
        .insert({
          ...base(alice.id),
          status: "resolved",
          resolved_by: "system",
          resolved_at: RESOLVED_AT,
        })
        .select("id")
        .single(),
      "a system-resolved finding",
    );
  });

  it("refuses a resolution dated in the future", async () => {
    const tomorrow = new Date(Date.now() + 86_400_000).toISOString();
    const result = await admin
      .from("privacy_findings")
      .insert({ ...base(alice.id), status: "resolved", resolved_by: "user", resolved_at: tomorrow })
      .select("id");

    expect(expectRejected(result, "a future resolution").code).toBe("23514");
  });

  it("refuses a rule id without a version, and the reverse", async () => {
    // ADR-001: a rule change must be recorded on the findings it generated, so
    // an unversioned rule id cannot be explained later.
    const missingVersion = await admin
      .from("privacy_findings")
      .insert({ ...base(alice.id), rule_id: "R-002", rule_version: null })
      .select("id");
    expect(expectRejected(missingVersion, "rule id without version").code).toBe("23514");

    const missingId = await admin
      .from("privacy_findings")
      .insert({ ...base(alice.id), rule_id: null, rule_version: "rules-v1" })
      .select("id");
    expect(expectRejected(missingId, "version without rule id").code).toBe("23514");
  });

  it("allows a demo-seeded finding with neither", async () => {
    // §7.5: `rule_id` is null for demo-seeded findings. ATL-018's dataset
    // illustrates the experience without claiming a rule evaluated it.
    expectOk(
      await admin
        .from("privacy_findings")
        .insert({ ...base(alice.id), rule_id: null, rule_version: null, source_type: "demo" })
        .select("id")
        .single(),
      "a demo-seeded finding",
    );
  });
});

describe("the vocabularies match the application", () => {
  it.each(FINDING_TYPES.map((entry) => entry.id))("accepts the %s category", async (type) => {
    expectOk(
      await admin
        .from("privacy_findings")
        .insert({ ...base(alice.id), finding_type: type })
        .select("id")
        .single(),
      `inserting a ${type} finding`,
    );
  });

  it("every application category satisfies the column's shape check", () => {
    // The database constrains the shape; the module constrains the meaning. A
    // vocabulary entry the column would reject is a defect that only appears at
    // insert time.
    for (const entry of FINDING_TYPES) {
      expect(isFindingTypeShape(entry.id)).toBe(true);
    }
  });

  // One test per column, each with an inline literal, for the same reason as the
  // lifecycle cases above: a table of loosely typed overrides checks nothing.
  it("refuses an out-of-vocabulary severity", async () => {
    const result = await admin
      .from("privacy_findings")
      .insert({ ...base(alice.id), severity: "catastrophic" })
      .select("id");

    expect(expectRejected(result, "a bad severity").code).toBe("23514");
  });

  it("refuses an out-of-vocabulary status", async () => {
    const result = await admin
      .from("privacy_findings")
      .insert({ ...base(alice.id), status: "snoozed" })
      .select("id");

    expect(expectRejected(result, "a bad status").code).toBe("23514");
  });

  it("refuses an out-of-vocabulary confidence", async () => {
    const result = await admin
      .from("privacy_findings")
      .insert({ ...base(alice.id), confidence: "certain" })
      .select("id");

    expect(expectRejected(result, "a bad confidence").code).toBe("23514");
  });

  it("refuses an out-of-vocabulary source_type", async () => {
    const result = await admin
      .from("privacy_findings")
      .insert({ ...base(alice.id), source_type: "guessed" })
      .select("id");

    expect(expectRejected(result, "a bad source_type").code).toBe("23514");
  });

  it("refuses an out-of-vocabulary resolved_by", async () => {
    const result = await admin
      .from("privacy_findings")
      .insert({
        ...base(alice.id),
        status: "resolved",
        resolved_by: "admin",
        resolved_at: RESOLVED_AT,
      })
      .select("id");

    expect(expectRejected(result, "a bad resolved_by").code).toBe("23514");
  });

  it("refuses a finding_type that fails the column's shape check", async () => {
    const result = await admin
      .from("privacy_findings")
      .insert({ ...base(alice.id), finding_type: "Not A Type" })
      .select("id");

    expect(expectRejected(result, "a malformed finding_type").code).toBe("23514");
  });
});

describe("resolution_action (ATL-042)", () => {
  /**
   * The column ATL-042 added, against real Postgres because both constraints
   * are the database's own and no double can prove them.
   */

  it("accepts every value in the closed vocabulary", async () => {
    for (const action of [
      "reviewed",
      "permission_revoked",
      "data_removed",
      "account_closed",
      "other",
    ]) {
      const result = await admin
        .from("privacy_findings")
        .insert({
          ...base(alice.id),
          dedup_key: `atl042-${action}-${Date.now()}`,
          status: "resolved",
          resolved_by: "user",
          resolved_at: RESOLVED_AT,
          resolution_action: action,
        })
        .select("resolution_action")
        .single();

      expect(expectOk(result, `resolving with ${action}`).resolution_action).toBe(action);
    }
  });

  it("refuses a value outside the vocabulary", async () => {
    // The second gate. The Server Action validates first; this is what stops a
    // value that bypassed it.
    const result = await admin
      .from("privacy_findings")
      .insert({
        ...base(alice.id),
        dedup_key: `atl042-bad-${Date.now()}`,
        status: "resolved",
        resolved_by: "user",
        resolved_at: RESOLVED_AT,
        resolution_action: "shrugged",
      })
      .select("id");

    expect(expectRejected(result, "an unknown resolution action").code).toBe("23514");
  });

  it("refuses an action on an open finding", async () => {
    // An action on something unresolved claims a decision nobody made.
    const result = await admin
      .from("privacy_findings")
      .insert({
        ...base(alice.id),
        dedup_key: `atl042-open-${Date.now()}`,
        resolution_action: "reviewed",
      })
      .select("id");

    expect(expectRejected(result, "an action on an open finding").code).toBe("23514");
  });

  it("refuses an action on a dismissed finding", async () => {
    /**
     * A dismissal is not a resolution: ADR-004 keeps its deduction until the
     * condition clears, so recording an "action taken" would misdescribe it.
     */
    const result = await admin
      .from("privacy_findings")
      .insert({
        ...base(alice.id),
        dedup_key: `atl042-dismissed-${Date.now()}`,
        status: "dismissed",
        resolved_by: "user",
        resolved_at: RESOLVED_AT,
        resolution_action: "reviewed",
      })
      .select("id");

    expect(expectRejected(result, "an action on a dismissed finding").code).toBe("23514");
  });

  it("allows a resolved finding with no action, for engine auto-resolution", async () => {
    // `resolved_by = 'system'` means nobody chose anything.
    const result = await admin
      .from("privacy_findings")
      .insert({
        ...base(alice.id),
        dedup_key: `atl042-system-${Date.now()}`,
        status: "resolved",
        resolved_by: "system",
        resolved_at: RESOLVED_AT,
      })
      .select("resolution_action")
      .single();

    expect(expectOk(result, "system resolution").resolution_action).toBeNull();
  });

  it("stays invisible to another user", async () => {
    // RLS is unchanged by the new column; this proves it covers it too.
    const row = expectOk(
      await admin
        .from("privacy_findings")
        .insert({
          ...base(alice.id),
          dedup_key: `atl042-rls-${Date.now()}`,
          status: "resolved",
          resolved_by: "user",
          resolved_at: RESOLVED_AT,
          resolution_action: "account_closed",
        })
        .select("id")
        .single(),
      "seeding a resolved finding",
    );

    const asBob = await bob.client
      .from("privacy_findings")
      .select("resolution_action")
      .eq("id", row.id);

    expect(asBob.data ?? []).toHaveLength(0);
  });
});
