import "server-only";

import { randomBytes, randomUUID } from "node:crypto";
import type { SupabaseClient } from "@supabase/supabase-js";
import type { Database } from "@/types/database.generated";
import {
  EncryptionKeyRepository,
  type EncryptionKeyRecord,
} from "@/server/repositories/encryption-key-repository";
import { createServiceRoleClient } from "@/server/db/service-role-client";
import { currentKek, kekForVersion } from "./kek";
import { CryptoError, KEY_BYTES, open, seal, zeroize, type EncryptionContext } from "./envelope";

/**
 * Per-user HMAC-SHA256 rejection key service (ATL-203, ADR-008 §8).
 *
 * A rejection key is a 256-bit secret stored in `user_encryption_keys` under
 * `key_purpose = 'rejection'`. It is used exclusively to produce and verify
 * rejection fingerprints — it is **never** an AES-GCM key.
 *
 * Key storage follows the same envelope-encryption pattern as DEKs: the raw
 * key material is wrapped with the current KEK before being written to the
 * database. The AAD binds the row id so that a wrapped rejection key cannot be
 * transplanted into a different row without breaking the tag.
 *
 * ## Creation
 *
 * Keys are created lazily on first call to `getOrCreate`. A user who never
 * rejects a candidate never gets a rejection key, consistent with ADR-003.
 *
 * ## Destruction
 *
 * `destroyAllForUser` on `EncryptionKeyRepository` is purpose-agnostic and
 * covers the rejection key as part of account deletion (ATL-082, ATL-203).
 *
 * ## Type safety
 *
 * `RejectionKey` is a branded `Buffer`. A plain `Buffer` is not assignable to
 * it without an explicit cast, preventing callers from accidentally passing an
 * AES-GCM DEK to an HMAC operation or vice versa.
 */

declare const __rejectionKeyBrand: unique symbol;

/**
 * A 256-bit HMAC-SHA256 key. Branded so it cannot be used as an AES-GCM key
 * by mistake (and so a plain `Buffer` cannot be passed where one is expected).
 */
export type RejectionKey = Buffer & { readonly [__rejectionKeyBrand]: "RejectionKey" };

const KEY_PURPOSE = "rejection" as const;

/**
 * Builds the AAD for a wrapped rejection key row.
 *
 * The column name is `wrapped_key` (not `wrapped_dek@${version}`) because:
 *  - the rejection key is not a DEK, and giving it the same AAD schema as a
 *    DEK would make it possible to transplant a wrapped rejection key into a
 *    content-key row without breaking authentication;
 *  - the recordId is the row UUID (pre-generated by the caller), not the
 *    userId, so the binding is tighter: the same key material wrapped for
 *    row A cannot be replayed into row B.
 */
function wrapContext(rowId: string): EncryptionContext {
  return { table: "user_encryption_keys", column: "wrapped_key", recordId: rowId };
}

export class RejectionKeyService {
  private readonly keys: EncryptionKeyRepository;

  constructor(db: SupabaseClient<Database>) {
    this.keys = new EncryptionKeyRepository(db);
  }

  /** Uses the service-role client — the only role that can reach the key table. */
  static create(): RejectionKeyService {
    return new RejectionKeyService(createServiceRoleClient());
  }

  /**
   * Returns the caller's active rejection key, creating one if this is the
   * first call for this user.
   *
   * A crypto-shredded user is refused rather than re-keyed, for the same
   * reason as `EncryptionService.writeDek`: re-keying after a shred
   * contradicts the ADR-003 guarantee that destruction is final.
   *
   * The row id is generated client-side before wrapping so it can be bound
   * into the AAD. A concurrent first-write races on the unique partial index
   * (`user_id, key_purpose WHERE status = 'active'`); the loser zeroizes its
   * candidate key and adopts the winner's.
   */
  async getOrCreate(userId: string): Promise<RejectionKey> {
    const existing = await this.keyState(userId);
    if (existing.destroyed) throw new CryptoError("key_destroyed");
    if (existing.active) return this.unwrap(existing.active);

    // Pre-generate the row id so the AAD can bind to it before the insert.
    const rowId = randomUUID();
    const kek = currentKek();
    const rawKey = randomBytes(KEY_BYTES);
    const wrapped = seal(kek.key, rawKey.toString("base64"), wrapContext(rowId));
    const created = await this.keys.insertActiveForPurpose(
      rowId,
      userId,
      wrapped,
      kek.version,
      KEY_PURPOSE,
    );

    // Deliberately not wrapped in try/finally on the winning path: on the
    // winning path this buffer is the return value, so zeroizing it would hand
    // the caller a zeroed key.
    if (created) return rawKey as RejectionKey;

    // Lost the race — discard our candidate and adopt the winner's.
    zeroize(rawKey);
    const winner = await this.keyState(userId);
    if (winner.destroyed) throw new CryptoError("key_destroyed");
    if (!winner.active) throw new CryptoError("key_unavailable");
    return this.unwrap(winner.active);
  }

  /**
   * Returns the caller's active rejection key without creating one.
   *
   * Used where a rejection key is required to already exist (e.g. fingerprint
   * verification). Fails closed: if no key exists or the key was destroyed,
   * throws rather than returning a placeholder.
   */
  async getRejectionKey(userId: string): Promise<RejectionKey> {
    const { active, destroyed } = await this.keyState(userId);
    if (destroyed) throw new CryptoError("key_destroyed");
    if (!active) throw new CryptoError("key_unavailable");
    return this.unwrap(active);
  }

  /**
   * Re-wraps rejection keys from an older KEK generation to the current one
   * (ADR-003, ADR-008 §5).
   *
   * Mirrors `EncryptionService.rotateKek` but uses `seal`/`open` with the
   * rejection-key AAD (`wrapContext(record.id)`) instead of `wrapDek`/
   * `unwrapDek`. The two operations use different AADs: content keys bind
   * `wrapped_dek@${version}` + `userId`; rejection keys bind `wrapped_key` +
   * `record.id`. Mixing them fails authentication.
   *
   * The key material itself is unchanged — only the wrapping changes.
   * Existing rejection fingerprints remain valid across rotations because
   * fingerprints depend on the raw key bytes, not the KEK wrapping.
   *
   * Idempotent and resumable. The `rewrap` guard on `expected kek_version`
   * prevents double-wrapping if two sweeps run concurrently.
   *
   * @returns how many rejection keys this batch re-wrapped.
   */
  async rotateKek(fromVersion: number, batchSize = 100): Promise<number> {
    const target = currentKek();
    if (fromVersion === target.version) return 0;

    const sourceKek = kekForVersion(fromVersion);
    const batch = await this.keys.listWrappedUnderByPurpose(KEY_PURPOSE, fromVersion, batchSize);

    let count = 0;
    for (const record of batch) {
      if (record.wrappedDek === null) continue;
      // `open` returns the base64-encoded key material (the plaintext inside
      // the envelope). `seal` re-encrypts it under the new KEK with the same
      // AAD, so the wrapping changes but the key material is unchanged.
      const rawBase64 = open(sourceKek, record.wrappedDek, wrapContext(record.id));
      const newWrapped = seal(target.key, rawBase64, wrapContext(record.id));
      if (await this.keys.rewrap(record.id, fromVersion, newWrapped, target.version)) count += 1;
    }

    return count;
  }

  /**
   * Classifies this user's rejection-key state.
   *
   * Scoped to `key_purpose = 'rejection'` so a destroyed content key cannot
   * interfere with rejection-key operations and vice versa. This is the mirror
   * of `EncryptionService.keyState`, which filters to `'content'`.
   */
  private async keyState(
    userId: string,
  ): Promise<{ active: EncryptionKeyRecord | null; destroyed: boolean }> {
    const rows = await this.keys.findForUserByPurpose(userId, KEY_PURPOSE);
    return {
      active: rows.find((r) => r.status === "active") ?? null,
      destroyed: rows.some((r) => r.status === "destroyed"),
    };
  }

  /**
   * Unwraps a rejection key row into raw key material.
   *
   * Validates the length after decoding to catch database corruption and
   * accidental swaps with content-key rows (which store base64-encoded
   * AES-256-GCM keys of the same length, but under a different AAD).
   */
  private unwrap(record: EncryptionKeyRecord): RejectionKey {
    // Defence in depth — keyState already routes destroyed rows away from here.
    if (record.wrappedDek === null) throw new CryptoError("key_destroyed");
    const kek = kekForVersion(record.kekVersion);
    const raw = Buffer.from(open(kek, record.wrappedDek, wrapContext(record.id)), "base64");
    if (raw.length !== KEY_BYTES) throw new CryptoError("invalid_key");
    return raw as RejectionKey;
  }
}
